version: '3.8'

services:
  mychat-room:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://shared-mongo:27017/mychat
      - DB_NAME=mychat
    networks:
      - mychat-net

networks:
  mychat-net:
    external: true
